### ISSUE TITLE
Urgently need a linux distribution release with the latest version

### ISSUE THREAD

**Issue by sfrechen** [Open-Systems-Pharmacology/rClr#12]
The latest release is only for windows. Urgently need a linux distribution.

**Comment by sfrechen** [comment]
I mean Version 0.9.1

@msevestre @Yuri05  @PavelBal

**Comment by PavelBal** [comment]
Don't have 0.9.1, but you could try 0.9.
[rClr_0.9.0_Ubuntu18.tar.gz](https://github.com/Open-Systems-Pharmacology/rClr/files/6748694/rClr_0.9.0_Ubuntu18.tar.gz)

**Comment by msevestre** [comment]
How do we create those packages anyways? What was the procedure so far?

**Comment by PavelBal** [comment]
The windows package can be built from source (some paths e.g. to visual studio must be adjusted). For Linux, Yuri did some magic with compiling the libraries in Linux and then copying them into source packages.

**Comment by msevestre** [comment]
I did ?? Lol getting old is getting boring

**Comment by PavelBal** [comment]
Did Yuri just accidentally confirmed that he and Michael are the same person? :D in that case - yepp, getting old and making mistakes a true spy would never make.

**Comment by Yuri05** [comment]
PAckages added.
