### ISSUE TITLE
Call garbage collection on clr

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/rClr#14]
Check if we can somehow enforce GC.

**Comment by IndrajeetPatil** [comment]
Maybe of relevance here:

![877A4C29-31AC-4EFB-AD71-FB7C36ED2B8C](https://user-images.githubusercontent.com/11330453/134470726-a50e2f5b-223e-4ef5-9bb4-838b82b6ffbe.jpeg)

**Comment by Yuri05** [comment]
S. also the discussion in https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/issues/261

@PavelBal Did you observe potential memory leaks / high memory usage in ospsuite-r (and that's why this issue)?

**Comment by PavelBal** [comment]
@Yuri05 Yes, I am observing similar issues you described in Open-Systems-Pharmacology/OSPSuite.ReportingEngine#261. RStudio consumes a lot of memory even after the simulations are finished (and e.g. the results are removed), and sometimes it just crashes. I did not investigate so far how to reproduce (we could write some dummy .net classes that would create huge objects), but calling garbage collector in R does not release the memory.

**Comment by Yuri05** [comment]
already implemented.
https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/c0e9c061225e96b08f829073025858ad4975f65b/R/utilities.R#L79-L90
