### ISSUE TITLE
Support R4.2

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/rClr#16]
Our latest release does not work with R4.2.

The package needs to be re-build with R4.2. I can do it for Windows. Should we increase the version to 0.9.2 or just create a new 0.9.1 rerlease with binaries built with R4.2?

**Comment by PavelBal** [comment]
@Yuri05 Could we please create a release for Windows with rClr built with R4.2 (I can send you the binary)? I would like to have a link to the release so we can download it e.g. with AppVeyor.

**Comment by Yuri05** [comment]
sure. I would create it as _prerelease_ first (until we have all the binaries for all OS)

So rClr compiled with R 4.1 does not work with R 4.2 anymore?

**Comment by PavelBal** [comment]
> So rClr compiled with R 4.1 does not work with R 4.2 anymore?

Yepp

**Comment by PavelBal** [comment]
Fixed in version 0.9.3

**Comment by myeusiyevich** [comment]
hello @PavelBal,

probably you could share 0.9.3 that works with 4.2?

**Comment by PavelBal** [comment]
Oh I meant 0.9.2: https://github.com/Open-Systems-Pharmacology/rClr/releases

Only the Windows version has been compiled.

**Comment by myeusiyevich** [comment]
Got it. Thanks.
