### ISSUE TITLE
Support for .NET Core

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/rClr#2]

**Comment by yurymaisiayonak** [comment]
Is there any plan to support rClr for .Net Core instead of Mono/DotNet Framework?

**Comment by UnclAlDeveloper** [comment]
Can I bump this also.  Is there planned support for this for .Net core and .Net 5/6?

**Comment by PavelBal** [comment]
We had some progresss migrating rClr to .NET 6. We currently do not have enough resources for this but will continue working on it in the future.

**Comment by PavelBal** [comment]
We are almost done re-implementing rClr with the support of .NET 8 - check out this repo: https://github.com/Open-Systems-Pharmacology/rSharp
