### ISSUE TITLE
Library will not load with ubuntu 20.04 due to mono version

### ISSUE THREAD

**Issue by Mitmischer** [Open-Systems-Pharmacology/rClr#6]
Hello,

I want to report my findings concerning ospsuite and ubuntu 20.04. `rClr` won't work in a vanilla ubuntu 20.04 installation, but the arising issue can be circumvented. I followed the steps given here: https://github.com/Open-Systems-Pharmacology/OSPSuite-R/wiki/Setup-ospsuite-R-on-Ubuntu, until the paragraph "Install R packages".
Then, I downloaded rClr from the releases-page, unzipped it and installed it. 
However, the package is broken. Trying to load the package, I get the following error:

```
> library(rClr)
Assembly '/usr/local/lib/R/site-library/rClr/libs/ClrFacade.dll' doesn't have an entry point.
Fehler: package or namespace load failed for ‘rClr’:
 .onLoad in loadNamespace() für 'rClr' fehlgeschlagen, Details:
  Aufruf: clrCallStatic("Rclr.RDotNetDataConverter", "SetRDotNet", setit)
  Fehler: Type:    System.DllNotFoundException
Message: System.Native assembly:<unknown assembly> type:<unknown type> member:(null)
Method:  
Stack trace:
  at (wrapper managed-to-native) Interop+Sys.LChflagsCanSetHiddenFlag()
  at Interop+Sys..cctor () [0x00000] in <12b418a7818c4ca0893feeaaf67f1e7f>:0 

> 
```

dotnet is at version 3.1.104, mono is at 6.8.0.105.

After downgrading mono to 5.18.1.3, everything does work like a charm, however. For downgrading Mono, the universe repository must be disabled, or the (more recent) mono version will be found. Having a permanently disabled universe repository is undesirable, which is why rClr should be made compabile with Mono 6 somewhen.

**Comment by Mitmischer** [comment]
Unfortunately, I have a follow-up. Loading a simulation in ospsuite ...

```
library(ospsuite)
sim = loadSimulation("sample.pkml")
```

... fails with:

```
Error in rClr::clrCall(simulationPersister, "LoadSimulation", expandPath(filePath)): Type:    System.DllNotFoundException
Message: libc
Method:  
Stack trace:
  at (wrapper managed-to-native) System.Drawing.GDIPlus.uname(intptr)
  at System.Drawing.GDIPlus..cctor () [0x0006e] in <15afd1d971d2426b9952bd183295c0c9>:0 


Traceback:

1. loadSimulation(simFilePath)
2. rClr::clrCall(simulationPersister, "LoadSimulation", expandPath(filePath))
```

The trace doesn't look that comprehensive, maybe you have the necessary experience for its interpretation?
The reference to libc is a bit puzzling to me. After this error message, I even installed `libc6-dev`, to no avail.

**Comment by Yuri05** [comment]
Can you try to (re)install the gdiplus library: `sudo apt-get install libgdiplus` (restart R after that).
No idea why ospsuite package (which is a purely command line) should try to load graphic libs though.

If it did not help, check this: https://www.mono-project.com/docs/gui/problemgdiplusinit/

**Comment by Mitmischer** [comment]
Thank you for the quick reply and the tip!

I reinstalled mono as per your suggestion (as `mono-complete` depends on `libgdiplus`), but the error remains.
Is there a way to start the ospsuite-binary (that the R-package ospsuite uses) directly? Then I could run ospsuite with debug libs or debug logging, as suggested in the link.

**Comment by Yuri05** [comment]
>Is there a way to start the ospsuite-binary (that the R-package ospsuite uses) directly?

No. You could write a small .NET wrapper and call it directly, but then you would bypass the rClr.
However you could debug directly from R, s. https://www.mono-project.com/docs/advanced/runtime/logging-runtime-events/

**Comment by Mitmischer** [comment]
Thanks a lot! On log level info, I got:
```
Mono: DllImport attempting to load: 'libc'.
Mono: DllImport error loading library '/usr/lib/mono/gac/System.Drawing/4.0.0.0__b03f5f7f11d50a3a/libc': '/usr/lib/mono/gac/System.Drawing/4.0.0.0__b03f5f7f11d50a3a/libc: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
Mono: DllImport error loading library '/usr/lib/mono/gac/System.Drawing/4.0.0.0__b03f5f7f11d50a3a/libc.so': '/usr/lib/mono/gac/System.Drawing/4.0.0.0__b03f5f7f11d50a3a/libc.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
Mono: DllImport error loading library '/usr/lib/R/bin/lib/libc': '/usr/lib/R/bin/lib/libc: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
Mono: DllImport error loading library '/usr/lib/R/bin/lib/libc.so': '/usr/lib/R/bin/lib/libc.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
Mono: DllImport error loading library 'libc': 'libc: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
Mono: DllImport error loading library 'libc.so': '/usr/lib/x86_64-linux-gnu/libc.so: Ungültiger ELF-Header'.
Mono: DllImport error loading library 'libc': 'libc: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
Mono: DllImport unable to load library 'libc: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
```

It turned out that on my system, /usr/lib/x86_64-linux-gnu/libc.so looks like this ...
```
/* GNU ld script
   Use the shared library, but some functions are only in
   the static library, so try that secondarily.  */
OUTPUT_FORMAT(elf64-x86-64)
GROUP ( /lib/x86_64-linux-gnu/libc.so.6 /usr/lib/x86_64-linux-gnu/libc_nonshared.a  AS_NEEDED ( /lib/x86_64-linux-gnu/ld-linux-x86-64.so.2 ) )
```

... which mono fails to interpret. This looks like a malformed import statement in the ospsuite package (https://stackoverflow.com/questions/14359981/mono-and-unmanaged-code-in-ubuntu) - so feel free to migrate the issue to that repo as rClr seems to be fine.

For me, I fixed the issue temporarily by:
```
sudo mkdir -p /usr/lib/R/bin/lib/
sudo ln -s /usr/lib/x86_64-linux-gnu/libc.so.6 /usr/lib/R/bin/lib/libc.so
```

Simulations can be loaded now :) They still don't run, but I'll open an issue at the ospsuite repo for that. Thank you! I'm leaving the issue open as the import statement should be fixed in ospsuite.

**Comment by Mitmischer** [comment]
Note that the original issue is still there (Mono 5 or earlier must be used). Sorry for mixing the two!

**Comment by PavelBal** [comment]
The development of this package is discontinued. Instead, check out our re-implementation of rClr - rSharp https://github.com/Open-Systems-Pharmacology/rSharp

That supports .NET 8.
